#!/usr/bin/env bash
#
# bootstrap installs things.

DOTFILES_ROOT="`pwd`"

set -e

echo ''

info () {
  printf "  [ \033[00;34m..\033[0m ] $1"
}

user () {
  printf "\r  [ \033[0;33m?\033[0m ] $1 "
}

success () {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

fail () {
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
  echo ''
  exit
}

title () {
  echo ''
  printf "  $1\n"
  echo ''
}

setup_gitconfig () {
  title 'Checking Git Config'

  if ! [ -f git/gitconfig.symlink ]
  then
    info 'setup gitconfig'

    git_credential='cache'
    if [ "$(uname -s)" == "Darwin" ]
    then
      git_credential='osxkeychain'
    fi

    user ' - What is your github author name?'
    read -e git_authorname
    user ' - What is your github author email?'
    read -e git_authoremail

    sed -e "s/AUTHORNAME/$git_authorname/g" -e "s/AUTHOREMAIL/$git_authoremail/g" -e "s/GIT_CREDENTIAL_HELPER/$git_credential/g" git/gitconfig.symlink.example > git/gitconfig.symlink

    success 'gitconfig'
  else
    success 'Git already configured!'
  fi
}

link_files () {
  ln -s $1 $2
  success "linked $1 to $2"
}

install_zshplugins () {
  title 'Installing ZSH plugins'

  declare -a plugins=("jocelynmallon/zshmarks" 
                      "iam4x/zsh-iterm-touchbar"
                      "zsh-users/zsh-autosuggestions")

  for plugin in "${plugins[@]}"
  do
    source="git://github.com/${plugin}.git"
    target=${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/${plugin#*/}

    if [ ! -d ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/${plugin#*/} ] 
    then
      info "Cloning ${source} into ${target}"
      eval $(echo "git clone ${source} ${target}")
      success "Cloned ${source} into ${target}"
    else
      success "skipping ${target}: already installed"
    fi
  done

  echo ''
  echo '  To complete the iTerm TouchBar integration:'
  echo '    Menu -> go into View -> Customize Tool Bar... and drag & drop the Fn module on the Touchbar'
  echo ''
}

install_dotfiles () {
  title 'Installing dotfiles'

  overwrite_all=false
  backup_all=false
  skip_all=false

  for source in `find $DOTFILES_ROOT -maxdepth 2 -name \*.symlink`
  do
    dest="$HOME/.`basename \"${source%.*}\"`"

    if [ -f $dest ] || [ -d $dest ]
    then

      overwrite=false
      backup=false
      skip=false

      if [ "$overwrite_all" == "false" ] && [ "$backup_all" == "false" ] && [ "$skip_all" == "false" ]
      then
        user "File already exists: `basename $source`, what do you want to do? [s]kip, [S]kip all, [o]verwrite, [O]verwrite all, [b]ackup, [B]ackup all?"
        read -n 1 action

        case "$action" in
          o )
            overwrite=true;;
          O )
            overwrite_all=true;;
          b )
            backup=true;;
          B )
            backup_all=true;;
          s )
            skip=true;;
          S )
            skip_all=true;;
          * )
            skip=true;;
        esac
      fi

      if [ "$overwrite" == "true" ] || [ "$overwrite_all" == "true" ]
      then
        rm -rf $dest
        success "removed $dest"
      fi

      if [ "$backup" == "true" ] || [ "$backup_all" == "true" ]
      then
        mv $dest $dest\.backup
        success "moved $dest to $dest.backup"
      fi

      if [ "$skip" == "false" ] && [ "$skip_all" == "false" ]
      then
        link_files $source $dest
      else
        success "skipped $source"
      fi

    else
      link_files $source $dest
    fi

  done
}

setup_macos() {
  title 'macOS defaults setup'
  user 'Want to setup macOS with some nice defaults? [Y/n]'
  read -n 1 action
  continue=false
  case "$action" in
    n )
      continue=false;;
    N )
      continue=false;;
    * )
      continue=true;;
  esac

  if [ "$continue" == "true" ]
  then
    success "Fine, let's continue the setup... You will be asked for your password.\n"  
    $HOME/.dotfiles/osx/set-defaults.sh
  else
    success "Ok, skipping macOS setup.\n"  
  fi
}

setup_gitconfig
install_dotfiles
install_zshplugins
setup_macos

title '.dotfiles ready & installed!'
echo '  Want to set up your laptop with the some developer essentials?'
echo '   => run `script/setup`'
echo ''
echo '  Want to reload your ZSH environment?'
echo '   => run `reload!`'
