#!/usr/bin/env sh
set +e
proceed=1
result=0

echo "\033[1;30m=================================================================
\033[0;37m               _                   _       _    __ _ _           
              (_)                 | |     | |  / _(_) |          
 _______ _ __  _  ___  _   _    __| | ___ | |_| |_ _| | ___  ___ 
|_  / _ \ '_ \| |/ _ \| | | |  / _\` |/ _ \| __|  _| | |/ _ \/ __|
 / /  __/ | | | | (_) | |_| | | (_| | (_) | |_| | | | |  __/\__ \\
/___\___|_| |_| |\___/ \__, |  \__,_|\___/ \__|_| |_|_|\___||___/
             _/ |       __/ |                                    
            |__/       |___/

\033[1;30m*****************************************************************
\033[1;37m         Let's install some interesting cli apps ...
\033[1;30m=================================================================
\033[1;37m"

while :; do
  case $1 in
    -h|--help) showhelp=1
    ;;
    *) break
  esac
  shift
done


success () {
  printf "\r\033[2K [ \033[00;32mok\033[0m ] $*\n"
}


info () {
  proceed=1
  printf "\r\033[2K [ \033[00;34m..\033[0m ] $1"
  message="$1"
}

user () {
  printf "\r\033[2K [ \033[00;33m?\033[0m ] $*"
}

fail () {
  printf "\r\033[2K [\033[0;31mFAIL\033[0m] $*\n"
  echo ''
  echo 'See /tmp/cli-tools-setup for more information.'
  exit 1
}

successfully() {
  if [[ $proceed -ne 0 ]]; then
    echo "We are proceeding with the command: $*" >> /tmp/cli-tools-setup 2>&1
    eval "$*" >> /tmp/cli-tools-setup 2>&1
    result=$?
    if [[ $result -ne 0 ]]; then
      fail "$message : failed" 2>&1
      exit 1
    else
      success "$message : installed"
    fi
  fi
}

check() {
  printf " [ \033[00;34m..\033[0m ] $1 : checking"
  echo "Checking $1, running $2:\n" >> /tmp/cli-tools-setup 2>&1
  eval "$2" > /dev/null 2>&1
  result=$?
  if [[ $result -ne 0 ]]; then
    proceed=1
    info "$1 : installing"
    message="$1"
  else
    proceed=0
    success "$1 : found"
  fi
}

echo "Feel free to follow the details by running:\n"
echo "\033[0m  tail -f /tmp/cli-tools-setup in another terminal"
message=""
echo ""
current_dir=$(pwd)
echo "\033[0;37mFirst some base stuff we need:\n"

check "homebrew" "command -v brew"
  successfully "exec bash -c 'echo | ruby -e \"$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)\"'"

check "python 2.x" "brew info python@2"
  successfully "brew install python@2"

check "python 3.x" "brew info python"
  successfully "brew install python"

echo "\n\033[1;37mNow the interesting things:\n"

check "jq (json processor)" "brew info jq"
  successfully "brew install jq"

check "howdoi (check stackoverflow)" "command -v howdoi"
  successfully "pip install howdoi"

check "haxor-news (hacker news reader)" "command -v hn"
  successfully "pip install haxor-news"

check "colorls (colorized ls command)" "gem list colorls | grep colorls"
  successfully "gem install colorls"

check "asciinema (record and share what happens in terminal)" "command -v asciinema"
  successfully "pip3 install asciinema"

check "googler (google cli)" "brew info googler"
  successfully "brew install googler"