#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $)"/..

sudo -v

# Keep-alive: update existing `sudo` time stamp until `.osx` has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

. $HOME/.dotfiles/osx/set-defaults.sh
. $HOME/.dotfiles/system/install.sh
. $HOME/.dotfiles/homebrew/install.sh
. $HOME/.dotfiles/ruby/install.sh