#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $)"/..

sudo -v

$HOME/.dotfiles/osx/set-defaults.sh
$HOME/.dotfiles/system/install.sh
$HOME/.dotfiles/homebrew/install.sh
$HOME/.dotfiles/ruby/install.sh