#!/usr/bin/env bash

set +e
proceed=1
result=0

DOTFILES_ROOT="$HOME/.dotfiles"
LOGFILE=/tmp/dotfiles-setup

. $DOTFILES_ROOT/script/shared-functions

if [[ $bootstrapping -ne 1 ]]; then
  header "Let's get ready for development ..."
fi

install_homebrew() {
  check "homebrew" "command -v brew"
  if [ "$(uname)" == "Darwin" ]; then
    successfully 'echo | ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"'
  elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
    if [[ $proceed -ne 0 ]]; then
      status "homebrew : ${BOLD}installing dependencies...${NORMAL}"
      successfully "sudo apt-get -y install build-essential curl file git ruby" >> $LOGFILE 2>&1;
      info "homebrew"
      status "homebrew : ${BOLD}installing${NORMAL}"
      successfully 'echo | sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"'
      info "homebrew" "environment ready"
      status "homebrew : ${BOLD}environment setup${NORMAL}"
      successfully 'test -d ~/.linuxbrew && eval $(~/.linuxbrew/bin/brew shellenv);test -d /home/linuxbrew/.linuxbrew && eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv);test -r ~/.bash_profile && echo "eval \$($(brew --prefix)/bin/brew shellenv)" >>~/.bash_profile;echo "eval \$($(brew --prefix)/bin/brew shellenv)" >>~/.profile;echo "eval \$($(brew --prefix)/bin/brew shellenv)" >>~/.localrc;sudo mkdir -p /home/linuxbrew/.linuxbrew/var/homebrew/linked;sudo chown -R $(whoami) /home/linuxbrew/.linuxbrew/var/homebrew/linked'
    fi
  fi
}

install_node() {
  check "node" "command -v node"
    successfully "brew install node"
  
  check "npm" "command -v npm"
    successfully "brew install npm"
  
  check "yarn" "command -v yarn"
    successfully "brew install yarn"
}

install_docker() {
  if [ "$(uname)" == "Darwin" ]; then
    check "docker for mac" "command -v docker"
      successfully "brew cask install docker"
  fi
}

install_ruby() {
  if [ "$(uname)" == "Darwin" ]; then
    check "rbenv" "ls /usr/local/rbenv > /dev/null" "cd /usr/local/rbenv && git pull"
    successfully "sudo git clone git://github.com/sstephenson/rbenv.git /usr/local/rbenv >> $LOGFILE 2>&1; sudo chgrp -R staff /usr/local/rbenv; sudo chmod -R g+rwxXs /usr/local/rbenv;"
  elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
    check "rbenv" "ls ~/.rbenv > /dev/null" "cd ~/.rbenv && git pull"
    successfully "git clone git://github.com/sstephenson/rbenv.git ~/.rbenv >> $LOGFILE 2>&1;"
  fi

  if [ "$(uname)" == "Darwin" ]; then
    check "ruby-build" "ls /usr/local/rbenv/plugins/ruby-build > /dev/null" "cd /usr/local/rbenv/plugins/ruby-build && git pull"
    successfully "mkdir -p /usr/local/rbenv/plugins; git clone git://github.com/sstephenson/ruby-build.git /usr/local/rbenv/plugins/ruby-build >> $LOGFILE 2>&1; sudo chgrp -R staff /usr/local/rbenv/plugins/ruby-build; sudo chmod -R g+rwxs /usr/local/rbenv/plugins/ruby-build;"
  elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
    check "ruby-build" "ls ~/.rbenv/plugins/ruby-build > /dev/null" "cd ~/.rbenv/plugins/ruby-build && git pull"
    successfully "mkdir -p ~/.rbenv/plugins; git clone git://github.com/sstephenson/ruby-build.git ~/.rbenv/plugins/ruby-build >> $LOGFILE 2>&1;"
  fi
  
  if [ -d "/usr/local/rbenv" ]; then
    export RBENV_ROOT="/usr/local/rbenv"
    export PATH="$RBENV_ROOT/bin:$RBENV_ROOT/shims:$PATH"
    eval "$(rbenv init -)"
  fi

  if [ -d "$HOME/.rbenv" ]; then
    export RBENV_ROOT="$HOME/.rbenv"
    export PATH="$RBENV_ROOT/bin:$RBENV_ROOT/shims:$PATH"
    eval "$(rbenv init -)"
  fi

  if [ "$(uname)" == "Darwin" ]; then
    check "ruby dependencies - openssl" "brew ls --versions openssl"
    successfully "brew install openssl"
    check "ruby dependencies - libyaml" "brew ls --versions libyaml"
    successfully "brew install libyaml"
    check "ruby dependencies - libffi" "brew ls --versions libffi"
    successfully "brew install libffi"
  elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
    info "ruby dependencies"
    status "ruby dependencies : ${BOLD}installing${NORMAL}"
    successfully "sudo apt-get install -y autoconf bison build-essential libssl-dev libyaml-dev libreadline6-dev zlib1g-dev libncurses5-dev libffi-dev libgdbm5 libgdbm-dev"
  fi

  check "ruby 2.5.3" "rbenv versions | grep 2.5.3"
    successfully "rbenv install 2.5.3; rbenv shell 2.5.3; gem install bundler"
}

install_vagrant() {
  if [ "$(uname)" == "Darwin" ]; then
    check "virtualbox" "command -v VirtualBox"
      successfully "brew cask install virtualbox"
    
    check "vagrant" "command -v vagrant"
      successfully "brew cask install vagrant"
  fi
}

setup_git() {
  bootstrapping=1 $HOME/.dotfiles/script/setup-git
}

setup_git
install_homebrew
install_node
install_ruby
install_docker
install_vagrant

if [[ $bootstrapping -ne 1 ]]; then
  _title_ "Done... Have fun!"
fi