#!/bin/bash

set +e
proceed=1
result=0

DOTFILES_ROOT="$HOME/.dotfiles"
LOGFILE=/tmp/dotfiles-setup

. $DOTFILES_ROOT/script/shared-functions

if [[ $bootstrapping -ne 1 ]]; then
  header "Let's get ready for development ..."
fi

install_homebrew() {
  check "homebrew" "command -v brew"
    successfully "exec bash -c 'echo | ruby -e \"$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)\"'"
}

install_node() {
  check "node" "command -v node"
    successfully "brew install node"
  
  check "npm" "command -v npm"
    successfully "brew install npm"
  
  check "yarn" "command -v yarn"
    successfully "brew install yarn"
}

install_docker() {
  check "docker for mac" "command -v docker"
    successfully "brew cask install docker"
}

install_ruby() {
  check "rbenv" "ls /usr/local/rbenv > /dev/null"
    successfully "sudo git clone git://github.com/sstephenson/rbenv.git /usr/local/rbenv >> $LOGFILE 2>&1; sudo chgrp -R staff /usr/local/rbenv; sudo chmod -R g+rwxXs /usr/local/rbenv; cd /usr/local/rbenv; git pull >> $LOGFILE 2>&1"

  check "ruby-build" "ls /usr/local/rbenv/plugins/ruby-build > /dev/null"
    successfully "mkdir -p /usr/local/rbenv/plugins; git clone git://github.com/sstephenson/ruby-build.git /usr/local/rbenv/plugins/ruby-build >> $LOGFILE 2>&1; sudo chgrp -R staff /usr/local/rbenv/plugins/ruby-build; sudo chmod -R g+rwxs /usr/local/rbenv/plugins/ruby-build; cd /usr/local/rbenv/plugins/ruby-build; git pull >> $LOGFILE 2>&1; cd $current_dir"

  check "ruby 2.5.3" "rbenv versions | grep 2.5.3"
    successfully "rbenv install 2.5.3; rbenv shell 2.5.3; gem install bundler"
}

install_vagrant() {
  check "virtualbox" "command -v VirtualBox"
    successfully "brew cask install virtualbox"
  
  check "vagrant" "command -v vagrant"
    successfully "brew cask install vagrant"
}

setup_git() {
  bootstrapping=1 $HOME/.dotfiles/script/setup-git
}

setup_git
install_homebrew
install_node
install_ruby
install_docker
install_vagrant

if [[ $bootstrapping -ne 1 ]]; then
  title "Done... Have fun!"
fi