#!/usr/bin/env bash

set +e
proceed=1
result=0

DOTFILES_ROOT="$HOME/.dotfiles"
LOGFILE=/tmp/dotfiles-setup

. $DOTFILES_ROOT/script/shared-functions

# ensure we capture unexpected exits
trap exit_warning EXIT

echo "Running in $0 $BASH_VERSION" >> $LOGFILE

if [[ $bootstrapping -ne 1 ]]; then
  header "Let's setup Git and Github ..."

  ask_sudo_password
fi

install_diff_so_fancy() {
  check "diff-so-fancy (beautiful git diff)" "command -v diff-so-fancy"
  successfully "brew install diff-so-fancy"
}

setup_gitconfig () {
  _title_ 'Checking Git Config'
  info 'setup gitconfig'

  git_credential='cache'
  if [[ "$(uname -s)" == "Darwin" ]]
  then
    git_credential='osxkeychain'
  fi

  while [[ -z "$git_authorname" ]]
  do
    user 'What is your github author name? '
    read -e git_authorname
  done
  while [[ -z "$git_authoremail" ]]
  do
    user 'What is your github author email? '
    read -e git_authoremail
  done

  sed -e "s/AUTHORNAME/$git_authorname/g" -e "s/AUTHOREMAIL/$git_authoremail/g" -e "s/GIT_CREDENTIAL_HELPER/$git_credential/g" $DOTFILES_ROOT/git/gitconfig.symlink.example > $DOTFILES_ROOT/git/gitconfig.symlink
  info "Installing .gitconfig"
  link_dotfile "$DOTFILES_ROOT/git/gitconfig.symlink"

  # When on windows configure core.autocrlf
  if [[ $(uname -r) =~ Microsoft$ ]]; then
    git config --global core.autocrlf true
  fi

  success 'Git successfully configured!'
}

maybe_generate_ssh_keys () {
  # Create a public key if need be.
  info_no_spinner "Checking for ssh keys:"
  mkdir -p ~/.ssh
  if [[ -e ~/.ssh/id_[rd]sa ]]
  then
    success "Found existing ssh keys"
  else
    ssh-keygen -q -N "" -t rsa -f ~/.ssh/id_rsa
    success "Generated an rsa ssh key at ~/.ssh/id_rsa"
  fi
}

copy_ssh_key () {
  if [[ -e ~/.ssh/id_rsa ]]; then
    source="$HOME/.ssh/id_rsa.pub"
  elif [[ -e ~/.ssh/id_dsa ]]; then
    source="$HOME/.ssh/id_dsa.pub"
  else
    error "no ssh public keys found"
    exit
  fi

  if command -v pbcopy >/dev/null 2>&1; then
    pbcopy < "$source"
  else
    printf "\nSorry, I could not copy the public key to the clipboard automatically. Please copy following key:\n\n"
    tput smam # enable line-wrapping
    cat "$source"
    tput rmam # prevent wrapping around again
    echo ""
    echo "(select the key and right click to copy)"
    echo ""
  fi
}

register_ssh_keys() {
  _title_ "Registering your ssh keys with Github"
  verify_ssh_auth
}

# checks to see that ssh keys are registered with github
# $1: "true"|"false" to end the auth cycle
verify_ssh_auth () {
  ssh_host="git@github.com"
  webpage_url="https://github.com/settings/ssh"
  instruction="Click 'Add SSH Key', paste into the box, and hit 'Add key'"

  notice "Checking for GitHub ssh authentication"
  if ! ssh -oStrictHostKeyChecking=no -T -v $ssh_host 2>&1 >/dev/null | grep \
    -q -e "Authentication succeeded (publickey)"
  then
    if [[ "$2" == "false" ]]  # error if auth fails twice in a row
    then
      error "Still no luck with GitHub ssh auth. Ask a dev!"
      ssh_auth_loop $webpage_url "false"
    else
      # otherwise prompt to upload keys
      notice "GitHub's ssh auth didn't seem to work\n"
      notice "Let's add your public key to GitHub:"
      notice "${BOLD}${instruction}${NORMAL}\n"
      ssh_auth_loop $webpage_url "true"
    fi
  else
    notice "GitHub ssh auth ${BOLD}succeeded${NORMAL}!"
  fi
}

ssh_auth_loop() {
  # a convenience function which lets you copy your public key to your clipboard
  # open the webpage for the site you're pasting the key into or just bailing
  # $1 = ssh key registration url
  service_url=$1
  first_run=$2
  if [[ "$first_run" == "true" ]]
  then
    notice "1. hit ${BOLD}o${NORMAL} to open GitHub on the web"
    notice "2. hit ${BOLD}c${NORMAL} to copy your public key to your clipboard"
    notice "3. hit ${BOLD}t${NORMAL} to test ssh auth for GitHub"
    notice "☢. hit ${BOLD}s${NORMAL} to skip ssh setup for GitHub\n"
    ssh_auth_loop $1 "false"
  else
    user "What's your choice? (o|c|t|s) "
    read -n 1 ssh_option
    case $ssh_option in
      o|O)
        success "opening GitHub's webpage to register your key!"
        if [[ $(uname -r) =~ Microsoft$ ]]; then
          explorer.exe $service_url
        else
          open $service_url
        fi
        ssh_auth_loop $service_url "false"
        ;;
      c|C)
        success "copying your ssh key to your clipboard"
        copy_ssh_key
        ssh_auth_loop $service_url "false"
        ;;
      t|T)
        printf "\r"
        verify_ssh_auth "false"
        ;;
      s|S)
        warn "skipping GitHub ssh registration"
        ;;
      *)
        ssh_auth_loop $service_url "false"
      ;;
    esac
  fi
}

install_diff_so_fancy
setup_gitconfig
maybe_generate_ssh_keys
register_ssh_keys

trap finish EXIT

if [[ $bootstrapping -ne 1 ]]; then
  _title_ "Done... Happy Coding!"
fi
