#!/usr/bin/env bash
set +e
proceed=1
result=0

DOTFILES_ROOT="$HOME/.dotfiles"
LOGFILE=/tmp/dotfiles-setup

. $DOTFILES_ROOT/script/shared-functions

echo "Running in $0 ${BASH_VERSION}" >> $LOGFILE

# ensure we capture unexpected exits
trap exit_warning EXIT

cli_apps=(
  "--Development Tools"

  "httpie|a user-friendly http client|command -v http|brew install httpie"
  "jq|json processor|command -v jq|brew install jq"
  "fx|json processor|command -v fx|brew install fx"
  "howdoi|check stackoverflow|command -v howdoi|pip install howdoi"
  "tldr|summarized command help|command -v tldr|npm install -g tldr"
  "mklicense|cli tool for generating licenses|command -v mklicense|npm install -g mklicense"
  "dockly|managing Docker containers|command -v dockly|npm install -g dockly"
  "serve|easy to use static file server|command -v serve|npm install -g serve"
  "add|itignore (generates a .gitignore for your project|command -v add-gitignore|npm install -g add-gitignore"
  "carbon|ow (beautiful images of your code|command -v carbon-now|npm i -g carbon-now-cli"
  "bat|a cat clone with wings|command -v bat|brew install bat"
  "ag|lightning-fast code search|command -v ag|brew install the_silver_searcher"
  "nnn|lightning fast, feature-packed file manager|command -v nnn|brew install nnn"

  "--Frontend Development"

  "caniuse|check caniuse.com|command -v caniuse|npm install -g caniuse-cmd"
  "pageres|capture screenshots of websites|command -v pageres|npm install -g pageres-cli"
  "capture-website|capture screenshots of websites|command -v capture-website|npm install -g capture-website-cli"
  "imgp|blazing fast image resizer and rotator|command -v imgp|pip3 install pillow"
  "chrunch|the best png size crusher|command -v crunch|brew install crunch"
  "imageoptim-cli|CLI for ImageOptim, ImageAlpha and JPEGmini|command -v imageoptim|npm install -g imageoptim-cli"

  "--Mobile Development"

  "mobicon|mobile app icon generator|command -v mobicon|npm install -g mobicon-cli"
  "mobisplash|mobile app splash screen generator|command -v mobisplash|npm install -g mobisplash-cli"
  "dframe|put device frames around app screenshots|command -v dframe|npm install -g deviceframe"
  "viewport-list|list of devices and their viewports|command -v viewport-list|npm install -g viewport-list-cli"

  "--Backend Development"

  "aws|universal cli for amazon web services|command -v aws|pip install awscli"
  "s3cmd|fully-featured s3 client|command -v s3cmd|pip install s3cmd"
  "loadtest|run a load test on the selected url|command -v loadtest|npm install -g loadtest"
  "speedtest-net|test your internet speed|command -v speedtest-net|npm install -g speedtest-net"
  "fast-cli|test your internet speed using fast.com|command -v fast|npm install -g fast-cli"
  "pretty-ms|convert milliseconds to a human readable string|command -v pretty-ms|npm install -g pretty-ms-cli"

  "--Git Things"

  "hub|tool that wraps git|command -v hub|brew install hub"
  "git-secret|stores private data inside a git repo|brew ls --versions git-secret|brew install git-secret"
  "git-extras|repo summary, repl, changelog, commit percentages, etc.|brew ls --versions git-extras|brew install git-extras"

  "--Git Things"

  "hub|tool that wraps git|command -v hub|brew install hub"
  "git-secret|stores private data inside a git repo|brew ls --versions git-secret|brew install git-secret"
  "git-extras|repo summary, repl, changelog, commit percentages, etc.|brew ls --versions git-extras|brew install git-extras"

  "--Convenience Stuff"

  "fkill|fabulously kill processes|command -v fkill|npm install -g fkill-cli"
  "colorls|colorized ls command|gem list colorls | grep colorls|gem install colorls"
  "gfi|google font installer|command -v gfi|npm install -g google-font-installer"
  "fuck|autocorrects error in previous command|command -v fuck|brew install thefuck"
  "undollar|undollar strips the dollar sign from copy/pasted commands|command -v $|npm install -g undollar"
  "kill-tabs|kill all Chrome tabs to improve performance|command -v kill-tabs|npm install -g kill-tabs"
  "autojump|cd command that learns where you went|command -v autojump|brew install autojump"
  "ffsend|Fully featured Firefox Send client|command -v ffsend|brew install ffsend"

  "--Information & Search"

  "bitly-client|make and manage bitly/zenjoy.me shortlinks|command -v bitly-client|npm install -g bitly-client"
  "haxor-news|hacker news reader|command -v hn|pip install haxor-news"
  "googler|google cli|command -v googler|brew install googler"
  "is-up|check website via isitup.org|command -v is-up|npm install -g is-up-cli"

  "--DevOps Stuff"

  "agrind|slice and dice log files on the command line|command -v agrind|brew install angle-grinder"

  "--OSX Management / Helpers"

  "m-cli|swiss army knife for macOS|command -v m|brew install m-cli"
  "mas-cli|command line interface for the Mac App Store|command -v mas|brew install mas"
  "brightness|manage screen brightness|command -v brightness|npm install -g brightness-cli"
  "volume|manage volume|command -v volume|npm install -g gillstrom/vol-cli"
  "battery-level|get battery level|command -v battery-level|npm install -g battery-level-cli"
  "screensaver|start screensaver|command -v screensaver|npm install -g screensaver"
  "organize|auto organize files based on file type|command -v organize|npm install -g organize-cli"
  "rename|utility for renaming files|command -v rename|npm install -g rename-cli"
  "trash|move files and folders to the trash|command -v trash|npm install -g trash-cli"
  "empty-trash|empty the trash|command -v empty-trash|npm install -g empty-trash-cli"
  "public-ip|get your public ip address|command -v public-ip|npm install -g public-ip-cli"
  "wallpaper|get or set your wallpaper|command -v wallpaper|npm install -g wallpaper-cli"

  "--Entertainment"

  "term-img|display images in iTerm|command -v term-img|npm install -g term-img-cli"
  "splash|beautiful wallpapers from unsplash|command -v splash|npm install -g splash-cli"
  "mplayer|command line music player|command -v mplayer|brew install mplayer"
  "youtube-dl|youtube downloader|command -v youtube-dl|brew install youtube-dl"
  "open-pip-cli|play movies in macos native picture-in-picture|command -v open-pip|npm install -g open-pip-cli"
  "mapscii|google maps in your terminal|command -v mapscii|npm install -g mapscii"
  "asciinema|record and share what happens in terminal|command -v asciinema|pip3 install asciinema"
  "cowsay|talk like a cow|command -v cowsay|brew install cowsay"
  "lolcat|talk in rainbows|command -v lolcat|gem install lolcat"
  "artii|asci art titles|command -v artii|gem install artii"
  "cat-names|get popular cat names|command -v cat-names|npm install -g cat-names"
  "dog-names|get popular dog names|command -v dog-names|npm install -g dog-names"
  "pokemon|get pokemon names|command -v pokemon|npm install -g pokemon-cli"
  "superheroes|get superheroes names|command -v superheroes|npm install -g superheroes-cli"
  "supervillains|get supervillains names|command -v supervillains|npm install -g supervillains-cli"
  "tetris|well... play tetris in the terminal|command -v tetris|brew install vitetris"
  "ohshit|helps you unfuck your git mistake|command -v ohshit|npm install -g ohshitgit"
)


function usage() {
  printf "This script installs various interesting command line apps.\n\n"
  printf "Usage: setup-cli-apps [options]\n\n"
  printf "Options\n"
  printf "  -l --list               Show list of apps that can be installed\n"
  printf "  -s --single-app <app>   Install app <app> only (use code as reference)\n"
  printf "\n"
}

install_homebrew() {
  check "homebrew" "command -v brew"
  if [[ "$(uname)" == "Darwin" ]]; then
    successfully 'echo | ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"'
  elif [[ "$(expr substr $(uname -s) 1 5)" == "Linux" ]]; then
    if [[ $proceed -ne 0 ]]; then
      status "homebrew : ${BOLD}installing dependencies...${NORMAL}"
      successfully "sudo apt-get update && sudo apt-get -y install build-essential curl file git ruby" >> $LOGFILE 2>&1;
      info "homebrew"
      status "homebrew : ${BOLD}installing${NORMAL}"
      successfully 'echo | sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"'
      info "homebrew" "environment ready"
      status "homebrew : ${BOLD}environment setup${NORMAL}"
      successfully 'test -d ~/.linuxbrew && eval $(~/.linuxbrew/bin/brew shellenv);test -d /home/linuxbrew/.linuxbrew && eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv);test -r ~/.bash_profile && echo "eval \$($(brew --prefix)/bin/brew shellenv)" >>~/.bash_profile;echo "eval \$($(brew --prefix)/bin/brew shellenv)" >>~/.profile;echo "eval \$($(brew --prefix)/bin/brew shellenv)" >>~/.localrc;sudo mkdir -p /home/linuxbrew/.linuxbrew/var/homebrew/linked;sudo chown -R $(whoami) /home/linuxbrew/.linuxbrew/var/homebrew/linked'
    fi
  fi
}

install_fundamentals() {
  check "node / npm" "command -v npm"
    successfully "brew install npm"

  check "python 2.x" "brew ls --versions python@2"
    successfully "brew install python@2"

  check "python 3.x" "brew ls --versions python@3"
    successfully "brew install python"
}

choose_cli_apps_loop() {
  user "Would you like to install [a]ll, [n]one, or [s]ome of the apps? [a/n/s]?"
  read -n 1 input
  case "$input" in
    [aA][lL][lL] | [aA])
      for app in "${cli_apps[@]}"; do
        IFS='|' read -r -a app_info <<< "$app"
        app_name="${app_info[0]}"
        app_description="${app_info[1]}"
        if [[ $app_name != --* ]]; then
          chosen_apps=("${chosen_apps[@]}" "${app}")
        fi
      done
      ;;
    [sS][oO][mM][eE] | [sS])
      echo ''
      for app in "${cli_apps[@]}"; do
        IFS='|' read -r -a app_info <<< "$app"
        app_name="${app_info[0]}"
        app_description="${app_info[1]}"
        if [[ $app_name != --* ]]; then
          user_ask_yn "Would you like to install ${BOLD}${app_name}${NORMAL} ${DIM}(${app_description})${NORMAL}?" "y"
          if [[ "$user_ask_yn_result" == "y" ]]; then
            chosen_apps=("${chosen_apps[@]}" "${app}")
          fi
        fi
      done
      ;;
    [nN][oO][nN][eE] | [nN])
      ;;
    *)
      info_no_spinner "Please choose ${BOLD}[a]${NORMAL}ll, ${BOLD}[n]${NORMAL}one, or ${BOLD}[s]${NORMAL}ome.\n"
      choose_cli_apps_loop
      ;;
  esac
}

show_possible_apps() {
  notice_left "${WHITE}We recommend installing following cli apps:\n"
  for app in "${cli_apps[@]}"; do
    IFS='|' read -r -a app_info <<< "$app"
    app_name="${app_info[0]}"
    app_description="${app_info[1]}"

    if [[ $app_name == --* ]]; then
      app_name="${app_name#*--}"
      printf "\n${BOLD}${YELLOW}%s${NORMAL}:\n\n" "${app_name}"
    else
      printf " - ${BOLD}%s${NORMAL} ${DIM}(%s)${NORMAL}\n" "${app_name}" "${app_description}"
    fi
  done
  echo ""
}

install_cli_apps() {
  chosen_apps=() # When the user opts to install a package it will be added to this array.

  if [[ -z "$1" ]]; then
    show_possible_apps
    choose_cli_apps_loop

    echo ""
  else
    IFS=',' read -r -a given_appnames <<< "$1"
    for selected in "${given_appnames[@]}"; do
      for app in "${cli_apps[@]}"; do
        IFS='|' read -r -a app_info <<< "$app"
        app_code="${app_info[0]}"
        if [[ "$app_code" == "$selected" ]]; then
          chosen_apps=("${chosen_apps[@]}" "${app}")
        fi
      done
    done
  fi

  if [ ${#chosen_apps[@]} -ne 0 ]; then
    function join_by { local d=$1; shift; echo -n "$1"; shift; printf "%s" "${@/#/$d}"; }

    chosen_apps_names=()
    for app in "${chosen_apps[@]}"; do
      IFS='|' read -r -a app_info <<< "$app"
      app_name="${app_info[0]}"
      chosen_apps_names=("${chosen_apps_names[@]}" "${app_name}")
    done
    chosen_apps_names_str=$(join_by ', ' "${chosen_apps_names[@]}")
    tput smam
    _title_ "Installing Selected Apps ${NORMAL}${DIM}(${chosen_apps_names_str})${NORMAL}"
    tput rmam
  fi

  for app in "${chosen_apps[@]}"; do
    IFS='|' read -r -a app_info <<< "$app"
    app_name="${app_info[0]}"
    app_description="${app_info[1]}"
    app_check="${app_info[2]}"
    app_installer="${app_info[3]}"

    check "$app_name" "$app_check"
    successfully "$app_installer" "perhaps it is already installed."
  done
}


while [[ "$1" == -* ]]; do
  case "$1" in
  -l|--list)
    show_possible_apps
    trap finish EXIT
    exit
    ;;
  -s|--single-app)
    shift
    install_cli_apps "$1"
    trap finish EXIT
    exit
    ;;
  -h|--help)
    usage
    trap finish EXIT
    exit 0
    ;;
  --)
    shift
    break
    ;;
  esac
  shift
done

if [[ $bootstrapping -ne 1 ]]; then
  header "Let's install some interesting cli apps ..."

  ask_sudo_password

  notice_left "\nFeel free to follow the details by running:"
  notice_left "${BOLD} tail -f $LOGFILE ${NORMAL}in another terminal\n"
fi

_title_ "First some base stuff, we just need:"

install_homebrew
install_fundamentals
install_cli_apps

trap finish EXIT

if [[ $bootstrapping -ne 1 ]]; then
  _title_ "Done... Have fun!"
fi